/**
 * The emoji this app offers, and the words that find them.
 *
 * Bundled rather than fetched: panel pages run under a CSP that allows no
 * external assets, and an emoji picker that needs a CDN is a picker that
 * breaks on exactly the pages that are shared with other people. It is also
 * why this is a curated list and not the whole of Unicode — the full set is
 * fifteen hundred entries whose keywords would have to be translated to be
 * findable, and a picker where "casa" finds nothing is worse than a shorter
 * one where it finds the house.
 *
 * Keywords are Spanish, lowercase and unaccented, because the search strips
 * accents before comparing: somebody typing "arbol" in a hurry should find the
 * tree. A few English words are kept where they are what people actually type
 * ("ok", "wifi", "email").
 */

export interface EmojiEntry {
  /** The character itself. */
  e: string;
  /** Space-separated search words. The first one is used as the tooltip. */
  k: string;
}

export interface EmojiCategory {
  /** Stable id, used by the tabs and by the i18n key. */
  id: string;
  /** One character, shown on the tab: a row of words would not fit. */
  tab: string;
  items: EmojiEntry[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: "faces",
    tab: "😀",
    items: [
      { e: "😀", k: "sonrisa cara feliz" },
      { e: "😃", k: "sonrisa alegre boca" },
      { e: "😄", k: "sonrisa ojos felices" },
      { e: "😁", k: "sonrisa dientes" },
      { e: "😆", k: "risa carcajada" },
      { e: "😅", k: "risa sudor alivio" },
      { e: "🤣", k: "risa suelo llorando" },
      { e: "😂", k: "risa lagrimas llorar" },
      { e: "🙂", k: "sonrisa leve" },
      { e: "🙃", k: "cara al reves ironia" },
      { e: "😉", k: "guino ojo" },
      { e: "😊", k: "sonrojo contento" },
      { e: "😇", k: "angel aureola santo" },
      { e: "🥰", k: "amor corazones enamorado" },
      { e: "😍", k: "ojos corazon amor" },
      { e: "🤩", k: "estrellas asombro fan" },
      { e: "😘", k: "beso" },
      { e: "😗", k: "beso silbar" },
      { e: "😋", k: "delicioso lengua rico" },
      { e: "😛", k: "lengua burla" },
      { e: "🤪", k: "loco chalado" },
      { e: "🤨", k: "ceja duda escepticismo" },
      { e: "🧐", k: "monoculo examinar" },
      { e: "🤓", k: "gafas empollon nerd" },
      { e: "😎", k: "gafas de sol guay" },
      { e: "🥸", k: "disfraz bigote" },
      { e: "🤯", k: "cabeza explota alucinar" },
      { e: "😳", k: "ruborizado sorpresa" },
      { e: "🥵", k: "calor sofoco" },
      { e: "🥶", k: "frio helado" },
      { e: "😱", k: "grito miedo panico" },
      { e: "😨", k: "miedo asustado" },
      { e: "😰", k: "ansiedad sudor" },
      { e: "😥", k: "triste alivio" },
      { e: "😢", k: "llorar triste lagrima" },
      { e: "😭", k: "llorar mucho pena" },
      { e: "😤", k: "resoplar enfado orgullo" },
      { e: "😠", k: "enfado enojado" },
      { e: "😡", k: "furia rojo ira" },
      { e: "🤬", k: "insulto palabrota" },
      { e: "😔", k: "pena decaido" },
      { e: "😞", k: "decepcion" },
      { e: "😟", k: "preocupado" },
      { e: "🙁", k: "descontento" },
      { e: "😖", k: "confuso agobio" },
      { e: "😣", k: "perseverar esfuerzo" },
      { e: "😩", k: "cansado hastio" },
      { e: "😫", k: "agotado harto" },
      { e: "🥱", k: "bostezo sueno aburrido" },
      { e: "😴", k: "dormir sueno zzz" },
      { e: "😪", k: "sueno somnoliento" },
      { e: "😌", k: "aliviado tranquilo" },
      { e: "😑", k: "sin expresion" },
      { e: "😐", k: "neutral serio" },
      { e: "😶", k: "sin boca callado" },
      { e: "🤐", k: "cremallera silencio" },
      { e: "🤔", k: "pensar duda mano" },
      { e: "🤗", k: "abrazo" },
      { e: "🤭", k: "ups tapar boca" },
      { e: "🤫", k: "silencio chist" },
      { e: "😬", k: "mueca incomodo" },
      { e: "😷", k: "mascarilla enfermo" },
      { e: "🤒", k: "termometro fiebre" },
      { e: "🤕", k: "herida venda" },
      { e: "🤢", k: "asco nausea" },
      { e: "🤮", k: "vomito" },
      { e: "🤧", k: "estornudo panuelo" },
      { e: "😵", k: "mareado aturdido" },
      { e: "🤠", k: "vaquero sombrero" },
      { e: "🥳", k: "fiesta celebracion gorro" },
      { e: "😈", k: "diablillo travieso" },
      { e: "👿", k: "diablo enfado" },
      { e: "💀", k: "calavera muerte" },
      { e: "☠️", k: "calavera huesos peligro" },
      { e: "👻", k: "fantasma" },
      { e: "👽", k: "alien extraterrestre" },
      { e: "🤖", k: "robot bot ia" },
      { e: "🎃", k: "calabaza halloween" },
      { e: "😺", k: "gato sonrisa" },
      { e: "😻", k: "gato amor" },
      { e: "🙈", k: "mono no veo" },
      { e: "🙉", k: "mono no oigo" },
      { e: "🙊", k: "mono no hablo" },
    ],
  },
  {
    id: "people",
    tab: "👋",
    items: [
      { e: "👋", k: "saludo hola adios mano" },
      { e: "🤚", k: "mano alzada" },
      { e: "✋", k: "mano parar" },
      { e: "🖐️", k: "mano dedos" },
      { e: "👌", k: "ok perfecto" },
      { e: "🤌", k: "dedos italiano" },
      { e: "🤏", k: "poco pellizco" },
      { e: "✌️", k: "victoria paz" },
      { e: "🤞", k: "dedos cruzados suerte" },
      { e: "🤟", k: "te quiero mano" },
      { e: "🤘", k: "cuernos rock" },
      { e: "🤙", k: "llamame" },
      { e: "👈", k: "izquierda senalar" },
      { e: "👉", k: "derecha senalar" },
      { e: "👆", k: "arriba senalar" },
      { e: "👇", k: "abajo senalar" },
      { e: "☝️", k: "indice arriba atencion" },
      { e: "👍", k: "bien pulgar arriba like" },
      { e: "👎", k: "mal pulgar abajo" },
      { e: "✊", k: "puno" },
      { e: "👊", k: "punetazo choque" },
      { e: "👏", k: "aplauso bravo" },
      { e: "🙌", k: "manos arriba celebrar" },
      { e: "👐", k: "manos abiertas" },
      { e: "🤝", k: "acuerdo apreton trato" },
      { e: "🙏", k: "gracias porfavor rezar" },
      { e: "✍️", k: "escribir mano" },
      { e: "💪", k: "fuerza musculo" },
      { e: "🦾", k: "brazo mecanico" },
      { e: "🧠", k: "cerebro idea" },
      { e: "👀", k: "ojos mirar" },
      { e: "👁️", k: "ojo" },
      { e: "👤", k: "persona silueta usuario" },
      { e: "👥", k: "personas grupo" },
      { e: "🧑", k: "persona" },
      { e: "👨", k: "hombre" },
      { e: "👩", k: "mujer" },
      { e: "🧒", k: "nino" },
      { e: "👶", k: "bebe" },
      { e: "🧓", k: "mayor abuelo" },
      { e: "👮", k: "policia" },
      { e: "🕵️", k: "detective espia" },
      { e: "👷", k: "obra casco trabajador" },
      { e: "🧑‍💻", k: "programador informatica" },
      { e: "🧑‍🍳", k: "cocinero chef" },
      { e: "🧑‍🏫", k: "profesor clase" },
      { e: "🧑‍⚕️", k: "medico sanitario" },
      { e: "🧑‍🌾", k: "agricultor campo" },
      { e: "🦸", k: "heroe superheroe" },
      { e: "🧙", k: "mago" },
      { e: "🎅", k: "papa noel navidad" },
      { e: "🚶", k: "andar caminar" },
      { e: "🏃", k: "correr prisa" },
      { e: "💃", k: "bailar" },
      { e: "🧘", k: "meditar yoga calma" },
    ],
  },
  {
    id: "nature",
    tab: "🌿",
    items: [
      { e: "🐶", k: "perro" },
      { e: "🐱", k: "gato" },
      { e: "🐭", k: "raton" },
      { e: "🐹", k: "hamster" },
      { e: "🐰", k: "conejo" },
      { e: "🦊", k: "zorro" },
      { e: "🐻", k: "oso" },
      { e: "🐼", k: "panda" },
      { e: "🐨", k: "koala" },
      { e: "🐯", k: "tigre" },
      { e: "🦁", k: "leon" },
      { e: "🐮", k: "vaca" },
      { e: "🐷", k: "cerdo" },
      { e: "🐸", k: "rana" },
      { e: "🐵", k: "mono" },
      { e: "🐔", k: "gallina pollo" },
      { e: "🐧", k: "pinguino" },
      { e: "🐦", k: "pajaro ave" },
      { e: "🦆", k: "pato" },
      { e: "🦉", k: "buho lechuza" },
      { e: "🦇", k: "murcielago" },
      { e: "🐺", k: "lobo" },
      { e: "🐗", k: "jabali" },
      { e: "🐴", k: "caballo" },
      { e: "🦄", k: "unicornio" },
      { e: "🐝", k: "abeja" },
      { e: "🐛", k: "gusano bicho bug" },
      { e: "🦋", k: "mariposa" },
      { e: "🐌", k: "caracol lento" },
      { e: "🐞", k: "mariquita bug" },
      { e: "🐜", k: "hormiga" },
      { e: "🕷️", k: "arana" },
      { e: "🐢", k: "tortuga" },
      { e: "🐍", k: "serpiente python" },
      { e: "🦎", k: "lagarto" },
      { e: "🐙", k: "pulpo" },
      { e: "🦑", k: "calamar" },
      { e: "🦐", k: "gamba" },
      { e: "🦀", k: "cangrejo" },
      { e: "🐟", k: "pez pescado" },
      { e: "🐬", k: "delfin" },
      { e: "🐳", k: "ballena" },
      { e: "🦈", k: "tiburon" },
      { e: "🐊", k: "cocodrilo" },
      { e: "🐘", k: "elefante" },
      { e: "🦒", k: "jirafa" },
      { e: "🐫", k: "camello" },
      { e: "🐑", k: "oveja" },
      { e: "🌵", k: "cactus" },
      { e: "🌲", k: "arbol pino bosque" },
      { e: "🌳", k: "arbol" },
      { e: "🌴", k: "palmera playa" },
      { e: "🌱", k: "brote planta crecer" },
      { e: "🌿", k: "hierba planta" },
      { e: "☘️", k: "trebol suerte" },
      { e: "🍀", k: "trebol cuatro suerte" },
      { e: "🍁", k: "hoja otono arce" },
      { e: "🍂", k: "hojas otono" },
      { e: "🌾", k: "espiga trigo" },
      { e: "🌷", k: "tulipan flor" },
      { e: "🌹", k: "rosa flor" },
      { e: "🌻", k: "girasol" },
      { e: "🌸", k: "flor cerezo" },
      { e: "💐", k: "ramo flores" },
      { e: "🌞", k: "sol cara dia" },
      { e: "🌝", k: "luna cara" },
      { e: "🌙", k: "luna noche" },
      { e: "⭐", k: "estrella favorito" },
      { e: "🌟", k: "estrella brillo" },
      { e: "✨", k: "brillos magia nuevo" },
      { e: "⚡", k: "rayo energia rapido" },
      { e: "🔥", k: "fuego llama urgente" },
      { e: "💧", k: "gota agua" },
      { e: "🌊", k: "ola mar" },
      { e: "❄️", k: "nieve copo frio" },
      { e: "☀️", k: "sol despejado" },
      { e: "⛅", k: "nubes sol" },
      { e: "☁️", k: "nube" },
      { e: "🌧️", k: "lluvia" },
      { e: "⛈️", k: "tormenta" },
      { e: "🌈", k: "arcoiris" },
      { e: "🌍", k: "mundo tierra europa" },
      { e: "🌎", k: "mundo america" },
      { e: "🌏", k: "mundo asia" },
    ],
  },
  {
    id: "food",
    tab: "🍎",
    items: [
      { e: "🍎", k: "manzana fruta" },
      { e: "🍏", k: "manzana verde" },
      { e: "🍐", k: "pera" },
      { e: "🍊", k: "naranja mandarina" },
      { e: "🍋", k: "limon" },
      { e: "🍌", k: "platano banana" },
      { e: "🍉", k: "sandia" },
      { e: "🍇", k: "uvas vino" },
      { e: "🍓", k: "fresa" },
      { e: "🫐", k: "arandanos" },
      { e: "🍒", k: "cerezas" },
      { e: "🍑", k: "melocoton" },
      { e: "🥭", k: "mango" },
      { e: "🍍", k: "pina" },
      { e: "🥥", k: "coco" },
      { e: "🥝", k: "kiwi" },
      { e: "🍅", k: "tomate" },
      { e: "🥑", k: "aguacate" },
      { e: "🥦", k: "brocoli" },
      { e: "🥕", k: "zanahoria" },
      { e: "🌽", k: "maiz" },
      { e: "🌶️", k: "picante chile" },
      { e: "🥔", k: "patata" },
      { e: "🧄", k: "ajo" },
      { e: "🧅", k: "cebolla" },
      { e: "🍄", k: "seta champinon" },
      { e: "🥜", k: "cacahuete" },
      { e: "🍞", k: "pan" },
      { e: "🥐", k: "croissant" },
      { e: "🥖", k: "baguette barra" },
      { e: "🧀", k: "queso" },
      { e: "🥚", k: "huevo" },
      { e: "🍳", k: "sarten huevo frito" },
      { e: "🥓", k: "bacon" },
      { e: "🍔", k: "hamburguesa" },
      { e: "🍟", k: "patatas fritas" },
      { e: "🍕", k: "pizza" },
      { e: "🌭", k: "perrito caliente" },
      { e: "🥪", k: "sandwich bocadillo" },
      { e: "🌮", k: "taco" },
      { e: "🌯", k: "burrito" },
      { e: "🥗", k: "ensalada" },
      { e: "🍜", k: "ramen sopa fideos" },
      { e: "🍝", k: "pasta espaguetis" },
      { e: "🍣", k: "sushi" },
      { e: "🥘", k: "paella cazuela" },
      { e: "🍲", k: "guiso olla" },
      { e: "🍿", k: "palomitas cine" },
      { e: "🧂", k: "sal" },
      { e: "🍦", k: "helado" },
      { e: "🍩", k: "donut" },
      { e: "🍪", k: "galleta" },
      { e: "🎂", k: "tarta cumpleanos" },
      { e: "🍰", k: "pastel porcion" },
      { e: "🍫", k: "chocolate" },
      { e: "🍬", k: "caramelo" },
      { e: "🍯", k: "miel" },
      { e: "☕", k: "cafe" },
      { e: "🍵", k: "te infusion" },
      { e: "🧃", k: "zumo brick" },
      { e: "🥤", k: "refresco vaso" },
      { e: "🍺", k: "cerveza" },
      { e: "🍻", k: "cervezas brindis" },
      { e: "🍷", k: "vino copa" },
      { e: "🥂", k: "brindis champan" },
      { e: "🍸", k: "cocktail copa" },
      { e: "🥃", k: "whisky" },
      { e: "🧊", k: "hielo cubito" },
    ],
  },
  {
    id: "activity",
    tab: "⚽",
    items: [
      { e: "⚽", k: "futbol balon" },
      { e: "🏀", k: "baloncesto" },
      { e: "🏈", k: "futbol americano" },
      { e: "⚾", k: "beisbol" },
      { e: "🎾", k: "tenis" },
      { e: "🏐", k: "voleibol" },
      { e: "🏉", k: "rugby" },
      { e: "🎱", k: "billar bola ocho" },
      { e: "🏓", k: "ping pong" },
      { e: "🏸", k: "badminton" },
      { e: "🥅", k: "porteria" },
      { e: "⛳", k: "golf bandera" },
      { e: "🏹", k: "arco flecha objetivo" },
      { e: "🎣", k: "pesca cana" },
      { e: "🥊", k: "boxeo guante" },
      { e: "🥋", k: "judo karate" },
      { e: "⛸️", k: "patinaje hielo" },
      { e: "🎿", k: "esqui" },
      { e: "🏂", k: "snowboard" },
      { e: "🏋️", k: "pesas gimnasio" },
      { e: "🤸", k: "gimnasia" },
      { e: "🚴", k: "bicicleta ciclismo" },
      { e: "🏊", k: "natacion nadar" },
      { e: "🧗", k: "escalada" },
      { e: "🏆", k: "trofeo ganador" },
      { e: "🥇", k: "oro primero medalla" },
      { e: "🥈", k: "plata segundo" },
      { e: "🥉", k: "bronce tercero" },
      { e: "🏅", k: "medalla" },
      { e: "🎯", k: "diana objetivo meta" },
      { e: "🎮", k: "videojuego mando" },
      { e: "🕹️", k: "joystick arcade" },
      { e: "🎲", k: "dado azar" },
      { e: "♟️", k: "ajedrez peon" },
      { e: "🧩", k: "puzzle pieza" },
      { e: "🎨", k: "arte pintura paleta" },
      { e: "🎭", k: "teatro mascaras" },
      { e: "🎬", k: "cine claqueta" },
      { e: "🎤", k: "microfono cantar" },
      { e: "🎧", k: "auriculares musica" },
      { e: "🎵", k: "musica nota" },
      { e: "🎶", k: "musica notas" },
      { e: "🎸", k: "guitarra" },
      { e: "🎹", k: "piano teclado" },
      { e: "🥁", k: "bateria tambor" },
      { e: "🎺", k: "trompeta" },
      { e: "🎻", k: "violin" },
      { e: "🎪", k: "circo carpa" },
      { e: "🎉", k: "fiesta confeti celebrar" },
      { e: "🎊", k: "confeti bola" },
      { e: "🎈", k: "globo" },
      { e: "🎁", k: "regalo" },
    ],
  },
  {
    id: "travel",
    tab: "✈️",
    items: [
      { e: "🚗", k: "coche auto" },
      { e: "🚕", k: "taxi" },
      { e: "🚙", k: "todoterreno suv" },
      { e: "🚌", k: "autobus" },
      { e: "🚎", k: "trolebus" },
      { e: "🏎️", k: "carreras formula" },
      { e: "🚓", k: "coche policia" },
      { e: "🚑", k: "ambulancia" },
      { e: "🚒", k: "bomberos camion" },
      { e: "🚚", k: "camion reparto" },
      { e: "🚜", k: "tractor" },
      { e: "🛵", k: "moto scooter" },
      { e: "🏍️", k: "moto" },
      { e: "🚲", k: "bicicleta" },
      { e: "🛴", k: "patinete" },
      { e: "🚂", k: "tren locomotora" },
      { e: "🚆", k: "tren" },
      { e: "🚇", k: "metro" },
      { e: "🚡", k: "teleferico" },
      { e: "✈️", k: "avion vuelo viaje" },
      { e: "🛫", k: "despegue avion" },
      { e: "🛬", k: "aterrizaje avion" },
      { e: "🚀", k: "cohete lanzamiento rapido" },
      { e: "🛸", k: "ovni platillo" },
      { e: "🚁", k: "helicoptero" },
      { e: "⛵", k: "velero barco" },
      { e: "🚤", k: "lancha" },
      { e: "🛳️", k: "crucero barco" },
      { e: "⚓", k: "ancla puerto" },
      { e: "🚏", k: "parada autobus" },
      { e: "🗺️", k: "mapa" },
      { e: "🧭", k: "brujula norte" },
      { e: "📍", k: "ubicacion pin lugar" },
      { e: "🏠", k: "casa hogar inicio" },
      { e: "🏡", k: "casa jardin" },
      { e: "🏢", k: "oficina edificio" },
      { e: "🏭", k: "fabrica industria" },
      { e: "🏥", k: "hospital" },
      { e: "🏦", k: "banco" },
      { e: "🏫", k: "colegio escuela" },
      { e: "🏨", k: "hotel" },
      { e: "🏪", k: "tienda 24h" },
      { e: "⛺", k: "camping tienda" },
      { e: "🏰", k: "castillo" },
      { e: "🗼", k: "torre" },
      { e: "🗽", k: "libertad estatua" },
      { e: "⛲", k: "fuente" },
      { e: "🏖️", k: "playa sombrilla" },
      { e: "🏔️", k: "montana nieve" },
      { e: "🌋", k: "volcan" },
      { e: "🏕️", k: "acampada" },
      { e: "🌃", k: "ciudad noche" },
      { e: "🌉", k: "puente noche" },
      { e: "🗿", k: "moai estatua" },
    ],
  },
  {
    id: "objects",
    tab: "💻",
    items: [
      { e: "💻", k: "portatil ordenador laptop" },
      { e: "🖥️", k: "ordenador pantalla" },
      { e: "🖨️", k: "impresora" },
      { e: "⌨️", k: "teclado" },
      { e: "🖱️", k: "raton mouse" },
      { e: "💾", k: "disquete guardar" },
      { e: "💿", k: "cd disco" },
      { e: "📀", k: "dvd disco" },
      { e: "💽", k: "minidisc" },
      { e: "🗜️", k: "comprimir zip" },
      { e: "📱", k: "movil telefono" },
      { e: "📲", k: "movil flecha" },
      { e: "☎️", k: "telefono fijo" },
      { e: "📞", k: "llamada auricular" },
      { e: "📟", k: "busca localizador" },
      { e: "📠", k: "fax" },
      { e: "🔋", k: "bateria" },
      { e: "🔌", k: "enchufe corriente" },
      { e: "💡", k: "idea bombilla" },
      { e: "🔦", k: "linterna" },
      { e: "🕯️", k: "vela" },
      { e: "📷", k: "camara foto" },
      { e: "📸", k: "camara flash" },
      { e: "📹", k: "videocamara" },
      { e: "🎥", k: "camara cine" },
      { e: "📺", k: "television tele" },
      { e: "📻", k: "radio" },
      { e: "🎙️", k: "micro podcast" },
      { e: "⏰", k: "alarma despertador" },
      { e: "⏱️", k: "cronometro" },
      { e: "⌛", k: "reloj arena tiempo" },
      { e: "⏳", k: "reloj arena espera" },
      { e: "🕐", k: "reloj hora" },
      { e: "📡", k: "antena satelite" },
      { e: "🔭", k: "telescopio" },
      { e: "🔬", k: "microscopio" },
      { e: "🧪", k: "probeta laboratorio" },
      { e: "🧬", k: "adn genetica" },
      { e: "💊", k: "pastilla medicina" },
      { e: "🩹", k: "tirita curita" },
      { e: "🔧", k: "llave inglesa arreglar" },
      { e: "🔨", k: "martillo" },
      { e: "🛠️", k: "herramientas ajustes" },
      { e: "⚙️", k: "engranaje ajustes config" },
      { e: "🧰", k: "caja herramientas" },
      { e: "🧲", k: "iman" },
      { e: "🔑", k: "llave clave acceso" },
      { e: "🗝️", k: "llave antigua" },
      { e: "🔒", k: "candado cerrado seguro" },
      { e: "🔓", k: "candado abierto" },
      { e: "🛡️", k: "escudo proteccion" },
      { e: "🔐", k: "candado llave privado" },
      { e: "📦", k: "caja paquete" },
      { e: "📫", k: "buzon correo" },
      { e: "📧", k: "email correo mail" },
      { e: "✉️", k: "sobre carta" },
      { e: "📨", k: "correo entrante" },
      { e: "📤", k: "bandeja salida enviar" },
      { e: "📥", k: "bandeja entrada recibir" },
      { e: "📝", k: "nota escribir apunte" },
      { e: "📄", k: "documento hoja" },
      { e: "📃", k: "documento texto" },
      { e: "📑", k: "marcadores pestanas" },
      { e: "📊", k: "grafico barras datos" },
      { e: "📈", k: "subida grafico crecer" },
      { e: "📉", k: "bajada grafico caer" },
      { e: "📋", k: "portapapeles lista" },
      { e: "📌", k: "chincheta fijar" },
      { e: "📎", k: "clip adjunto" },
      { e: "🔗", k: "enlace link cadena" },
      { e: "📚", k: "libros biblioteca" },
      { e: "📖", k: "libro leer" },
      { e: "📓", k: "cuaderno" },
      { e: "🔖", k: "marcador bookmark" },
      { e: "🏷️", k: "etiqueta tag" },
      { e: "💰", k: "dinero bolsa" },
      { e: "💳", k: "tarjeta pago" },
      { e: "🧾", k: "recibo factura" },
      { e: "✂️", k: "tijeras cortar" },
      { e: "🖊️", k: "boligrafo" },
      { e: "✏️", k: "lapiz editar" },
      { e: "🖍️", k: "cera color" },
      { e: "🗑️", k: "papelera borrar basura" },
      { e: "🗄️", k: "archivador ficheros" },
      { e: "📁", k: "carpeta" },
      { e: "📂", k: "carpeta abierta" },
      { e: "🗂️", k: "carpetas separadores" },
      { e: "🔍", k: "buscar lupa" },
      { e: "🔎", k: "buscar lupa derecha" },
      { e: "🪟", k: "ventana" },
      { e: "🛒", k: "carro compra" },
      { e: "🧹", k: "escoba limpiar" },
    ],
  },
  {
    id: "symbols",
    tab: "✅",
    items: [
      { e: "✅", k: "hecho check ok correcto" },
      { e: "☑️", k: "casilla marcada" },
      { e: "✔️", k: "check marca" },
      { e: "❌", k: "error mal cruz no" },
      { e: "❎", k: "cruz cuadro" },
      { e: "⚠️", k: "aviso atencion cuidado" },
      { e: "🚫", k: "prohibido no" },
      { e: "⛔", k: "prohibido paso" },
      { e: "❗", k: "exclamacion importante" },
      { e: "❓", k: "pregunta duda" },
      { e: "💬", k: "comentario bocadillo chat" },
      { e: "💭", k: "pensamiento nube" },
      { e: "🗯️", k: "enfado bocadillo" },
      { e: "🔔", k: "campana aviso notificacion" },
      { e: "🔕", k: "silencio campana" },
      { e: "📢", k: "megafono anuncio" },
      { e: "📣", k: "megafono animar" },
      { e: "♻️", k: "reciclar" },
      { e: "🔄", k: "actualizar sincronizar" },
      { e: "🔁", k: "repetir bucle" },
      { e: "▶️", k: "reproducir play" },
      { e: "⏸️", k: "pausa" },
      { e: "⏹️", k: "parar stop" },
      { e: "⏭️", k: "siguiente" },
      { e: "⏮️", k: "anterior" },
      { e: "⬆️", k: "arriba flecha" },
      { e: "⬇️", k: "abajo flecha" },
      { e: "⬅️", k: "izquierda flecha" },
      { e: "➡️", k: "derecha flecha" },
      { e: "↩️", k: "volver atras" },
      { e: "🔺", k: "triangulo arriba" },
      { e: "🔻", k: "triangulo abajo" },
      { e: "🔴", k: "rojo circulo" },
      { e: "🟠", k: "naranja circulo" },
      { e: "🟡", k: "amarillo circulo" },
      { e: "🟢", k: "verde circulo ok" },
      { e: "🔵", k: "azul circulo" },
      { e: "🟣", k: "morado circulo" },
      { e: "⚫", k: "negro circulo" },
      { e: "⚪", k: "blanco circulo" },
      { e: "🟥", k: "rojo cuadrado" },
      { e: "🟩", k: "verde cuadrado" },
      { e: "🟦", k: "azul cuadrado" },
      { e: "❤️", k: "corazon rojo amor" },
      { e: "🧡", k: "corazon naranja" },
      { e: "💛", k: "corazon amarillo" },
      { e: "💚", k: "corazon verde" },
      { e: "💙", k: "corazon azul" },
      { e: "💜", k: "corazon morado" },
      { e: "🖤", k: "corazon negro" },
      { e: "💔", k: "corazon roto" },
      { e: "⭕", k: "circulo rojo" },
      { e: "💯", k: "cien perfecto" },
      { e: "🆕", k: "nuevo new" },
      { e: "🆗", k: "ok" },
      { e: "🆓", k: "gratis free" },
      { e: "🔝", k: "arriba top" },
      { e: "#️⃣", k: "almohadilla" },
      { e: "*️⃣", k: "asterisco" },
      { e: "1️⃣", k: "uno numero" },
      { e: "2️⃣", k: "dos numero" },
      { e: "3️⃣", k: "tres numero" },
      { e: "©️", k: "copyright" },
      { e: "®️", k: "registrado" },
      { e: "™️", k: "marca registrada" },
      { e: "〽️", k: "parte alterna" },
      { e: "⚕️", k: "medicina salud" },
      { e: "♾️", k: "infinito" },
      { e: "⚖️", k: "balanza justicia" },
      { e: "🔞", k: "adultos" },
      { e: "📶", k: "cobertura senal" },
      { e: "📳", k: "vibracion" },
      { e: "🔇", k: "silencio mute" },
      { e: "🔊", k: "volumen alto" },
      { e: "🌐", k: "web internet globo" },
      { e: "🔤", k: "letras abc" },
      { e: "🔢", k: "numeros" },
    ],
  },
];

/** Every entry, flattened, for searching across categories. */
export const ALL_EMOJI: EmojiEntry[] = EMOJI_CATEGORIES.flatMap((c) => c.items);

/** What the picker shows before anything has been used. */
export const DEFAULT_RECENT = [
  "🔖",
  "⭐",
  "🏠",
  "💡",
  "✅",
  "⚠️",
  "🔥",
  "📌",
  "📝",
  "🔗",
  "🚀",
  "❤️",
];

/**
 * Accents off, lowercase.
 *
 * Somebody typing "arbol" in a hurry should find the tree, and somebody typing
 * "árbol" properly should find it too. Normalising both sides is the only way
 * both work, and it is cheaper than writing every keyword twice.
 */
export function foldText(input: string): string {
  return input
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "");
}
