/**
 * Curated emoji list shared by the icon library and the panel tab-icon picker.
 *
 * Bundled instead of pulled from a package or a CDN: the app ships no external
 * assets and public panels run under a strict CSP. `k` holds Spanish keywords
 * so searching "casa" or "cohete" works.
 */
export interface LibraryEmoji {
  e: string;
  k: string;
}

export const LIBRARY_EMOJIS: LibraryEmoji[] = [
  { e: "🔖", k: "marcador bookmark" },
  { e: "⭐", k: "estrella favorito" },
  { e: "🏠", k: "casa inicio home" },
  { e: "📁", k: "carpeta archivo" },
  { e: "📂", k: "carpeta abierta" },
  { e: "📚", k: "libros biblioteca" },
  { e: "📖", k: "libro lectura" },
  { e: "💼", k: "trabajo maletin" },
  { e: "🚀", k: "cohete lanzamiento" },
  { e: "🔥", k: "fuego popular" },
  { e: "💡", k: "idea bombilla" },
  { e: "✅", k: "check hecho ok" },
  { e: "🎯", k: "diana objetivo" },
  { e: "🧠", k: "cerebro aprender" },
  { e: "💻", k: "portatil ordenador codigo" },
  { e: "🖥️", k: "monitor ordenador" },
  { e: "📝", k: "notas escribir" },
  { e: "📊", k: "grafico datos metricas" },
  { e: "📈", k: "grafico subida" },
  { e: "📅", k: "calendario fecha" },
  { e: "📌", k: "chincheta fijar" },
  { e: "🗂️", k: "archivador carpetas" },
  { e: "🔍", k: "lupa buscar" },
  { e: "🔗", k: "enlace link" },
  { e: "⚙️", k: "ajustes engranaje config" },
  { e: "🛠️", k: "herramientas" },
  { e: "🧪", k: "laboratorio pruebas test" },
  { e: "🐛", k: "bug error insecto" },
  { e: "🎓", k: "estudio graduacion universidad" },
  { e: "🎮", k: "videojuegos juego" },
  { e: "🎬", k: "cine peliculas" },
  { e: "🎵", k: "musica nota" },
  { e: "🎧", k: "auriculares musica podcast" },
  { e: "📺", k: "television series" },
  { e: "🍿", k: "palomitas cine" },
  { e: "⚽", k: "futbol deporte" },
  { e: "🏋️", k: "gimnasio deporte pesas" },
  { e: "🍳", k: "cocina recetas huevo" },
  { e: "🍕", k: "pizza comida" },
  { e: "☕", k: "cafe bebida" },
  { e: "🌱", k: "planta jardin" },
  { e: "✈️", k: "viajes avion" },
  { e: "🏖️", k: "playa vacaciones" },
  { e: "🎨", k: "arte diseño pintura" },
  { e: "📷", k: "camara fotos" },
  { e: "❤️", k: "corazon amor" },
  { e: "⚡", k: "rayo rapido energia" },
  { e: "🌟", k: "estrella brillo" },
  { e: "🌈", k: "arcoiris" },
  { e: "🌍", k: "mundo tierra global" },
  { e: "🔒", k: "candado privado seguro" },
  { e: "🔑", k: "llave acceso" },
  { e: "🏷️", k: "etiqueta tag" },
  { e: "📦", k: "caja paquete" },
  { e: "♻️", k: "reciclar" },
  { e: "🧩", k: "puzzle pieza" },
  { e: "🐉", k: "dragon" },
  { e: "🐱", k: "gato" },
  { e: "🐶", k: "perro" },
  { e: "🦊", k: "zorro" },
  { e: "🐧", k: "pinguino" },
  { e: "🐢", k: "tortuga" },
  { e: "🐠", k: "pez pecera" },
  { e: "🦉", k: "buho" },
  { e: "🌵", k: "cactus" },
  { e: "🌸", k: "flor sakura" },
  { e: "🍁", k: "hoja otoño" },
  { e: "🌙", k: "luna noche" },
  { e: "☀️", k: "sol dia" },
  { e: "🌊", k: "ola mar oceano" },
  { e: "❄️", k: "nieve frio" },
  { e: "💰", k: "dinero finanzas" },
  { e: "🏦", k: "banco" },
  { e: "🏥", k: "salud hospital medico" },
  { e: "🛒", k: "compras carrito" },
  { e: "📧", k: "email correo" },
  { e: "🗺️", k: "mapa" },
];
